import { EventFormat } from "@/lib/types";

export const events: EventFormat[] = [
  {
    id: "founder-discovery-night",
    title: "Founder Discovery Night",
    purpose:
      "Introduce entrepreneurship, ASES, HackEurope, and the opportunity to build.",
    length: "90 minutes",
    difficulty: "Easy",
    bestTiming: "4–8 weeks before HackEurope deadline",
    agenda: [
      "0–10 min: Welcome",
      "10–20 min: ASES x HackEurope intro",
      "20–35 min: Talk: how student builders become founders",
      "35–55 min: Problem discovery exercise",
      "55–70 min: Idea-sharing in small groups",
      "70–80 min: HackEurope opportunity",
      "80–90 min: QR sign-up and team matching",
    ],
    requiredOutputs: [
      "Attendance list",
      "HackEurope interest form responses",
      "Students with ideas",
      "Students looking for teammates",
      "Event photos",
      "Post-event report",
    ],
  },
  {
    id: "problem-discovery-sprint",
    title: "Problem Discovery Sprint",
    purpose:
      "Help students move from vague ideas to specific user problems.",
    length: "2 hours",
    difficulty: "Medium",
    agenda: [
      "0–10 min: Welcome",
      "10–25 min: Painkiller vs vitamin",
      "25–45 min: User/problem mapping",
      "45–70 min: Peer interviews",
      "70–90 min: Rewrite idea as problem statement",
      "90–110 min: Group feedback",
      "110–120 min: Next steps",
    ],
    requiredOutputs: [
      'Completed problem statement: "We are solving [specific problem] for [specific user] who currently struggles with [existing workaround], and this matters because [consequence]."',
      "Attendance list",
      "Post-event report",
    ],
  },
  {
    id: "team-formation-night",
    title: "Team Formation Night",
    purpose: "Help students find teammates before HackEurope.",
    length: "90 minutes",
    difficulty: "Easy",
    agenda: [
      "0–10 min: Welcome and format explanation",
      "10–40 min: Student intros (Name, Degree, Skill, Sector, What to build, Teammates needed)",
      "40–65 min: Open team matching",
      "65–80 min: Team confirmation and brief pitches",
      "80–90 min: Application clinic invite and next steps",
    ],
    requiredOutputs: [
      "Team matching spreadsheet",
      "List of formed teams",
      "Solo students still looking",
      "Application clinic invite list",
    ],
  },
  {
    id: "build-night",
    title: "Build Night",
    purpose: "Get students building before HackEurope.",
    length: "2–3 hours",
    difficulty: "Medium",
    agenda: [
      "0–10 min: Welcome and framing",
      "10–20 min: Problem statement review",
      "20–30 min: Team check-in and scoping",
      "30–120+ min: Build time (design/code/prototype)",
      "Last 20 min: Demo what was built",
    ],
    requiredOutputs: [
      "Team name",
      "Team members",
      "Problem statement",
      "What they built",
      "Demo / Figma / GitHub / screenshot link",
      "Whether they plan to apply to HackEurope",
    ],
  },
  {
    id: "mini-hackathon",
    title: "Mini-Hackathon",
    purpose: "Simulate HackEurope locally.",
    length: "Half-day / Full-day / Weekend",
    difficulty: "High",
    agenda: [
      "Opening: Briefing and team confirmation",
      "Phase 1: Problem statement and scoping",
      "Phase 2: Building and prototyping",
      "Phase 3: Demo and judging",
      "Closing: Feedback, prizes, and HackEurope application reminder",
    ],
    requiredOutputs: [
      "Final team list",
      "Prototypes / demo links",
      "Judge feedback notes",
      "Event photos / videos",
      "HackEurope application interest list",
      "Post-event report",
    ],
  },
  {
    id: "hackeurope-application-clinic",
    title: "HackEurope Application Clinic",
    purpose:
      "Convert interested students into actual HackEurope applicants.",
    length: "60–90 minutes",
    difficulty: "Easy",
    bestTiming: "1–2 weeks before HackEurope deadline",
    agenda: [
      "0–10 min: Welcome",
      "10–20 min: What HackEurope is looking for",
      "20–35 min: How to position your background and project",
      "35–60 min: Application writing time",
      "60–80 min: Peer and facilitator feedback",
      "80–90 min: Submission reminder and deadline confirmation",
    ],
    requiredOutputs: [
      "Students attending clinic",
      "Applications started",
      "Applications submitted",
      "Common barriers identified",
      "Students still needing teammates",
    ],
  },
  {
    id: "post-hackeurope-reunion",
    title: "Post-HackEurope Reunion",
    purpose: "Retain talent after HackEurope.",
    length: "60–90 minutes",
    difficulty: "Easy",
    agenda: [
      "0–15 min: Welcome back and introductions",
      "15–40 min: HackEurope experience sharing",
      "40–60 min: Project updates and next steps",
      "60–80 min: Future ASES opportunities",
      "80–90 min: Community building and closes",
    ],
    requiredOutputs: [
      "List of students who attended HackEurope",
      "Testimonials",
      "Event photos",
      "Project updates",
      "Students interested in future ASES opportunities",
    ],
  },
];
