import { OperationsTool } from "@/lib/types";

export const operationsTools: OperationsTool[] = [
  {
    id: "partner-application-form",
    title: "Local Partner Application Form",
    purpose: "Used when a university society wants to join the programme.",
    fields: [
      "Society name",
      "University",
      "Country / city",
      "Main contact name",
      "Email address",
      "Role in society",
      "Society type (entrepreneurship, AI, coding, etc.)",
      "Membership size",
      "Previous event experience",
      "Can you reach technical students?",
      "Preferred event format",
      "Proposed timeline",
      "Why they want to join",
      "Can they host at least two events?",
      "Can they submit reports within 72 hours?",
    ],
  },
  {
    id: "post-event-report-form",
    title: "Post-Event Report Form",
    purpose:
      "Submitted by local partners within 72 hours after every event.",
    fields: [
      "University",
      "Society name",
      "Event type",
      "Event date",
      "Number of attendees",
      "Number of technical students",
      "Number of teams formed",
      "Number interested in HackEurope",
      "Number of applications started",
      "Number of applications submitted",
      "Photos / Google Drive link",
      "Event feedback",
      "Challenges encountered",
      "Support needed from ASES HQ",
    ],
  },
  {
    id: "hackeurope-interest-form",
    title: "HackEurope Interest Form",
    purpose:
      "Student-facing form used during local events via QR code.",
    fields: [
      "Full name",
      "University",
      "Degree / field of study",
      "Year of study",
      "Email address",
      "LinkedIn profile",
      "Role: technical / product / business / design",
      "Do you have a team?",
      "Are you looking for teammates?",
      "Are you interested in applying to HackEurope?",
      "Application status: not started / started / submitted",
      "Project idea (if any)",
    ],
  },
  {
    id: "partner-pipeline-sheet",
    title: "Partner Pipeline Sheet",
    purpose:
      "ASES HQ master tracker for all prospective and active partners.",
    tracks: [
      "University",
      "Society name",
      "Country",
      "Main contact",
      "Status (Targeted / Contacted / Replied / Call Scheduled / Onboarded / Event Planned / Event Completed / Report Submitted / Dormant)",
      "Priority level",
      "Next action",
      "Risk flag",
      "Notes",
    ],
  },
  {
    id: "event-tracker-sheet",
    title: "Event Tracker Sheet",
    purpose: "Tracks all partner events and their outputs.",
    tracks: [
      "University",
      "Event type",
      "Event date",
      "Expected attendees",
      "Actual attendees",
      "Students interested in HackEurope",
      "Applications started",
      "Applications submitted",
      "Report submission status",
    ],
  },
  {
    id: "conversion-dashboard-sheet",
    title: "Conversion Dashboard Sheet",
    purpose:
      "Aggregates data to calculate programme-wide conversion rates.",
    tracks: [
      "Total attendees across all events",
      "Total students who expressed HackEurope interest",
      "Total applications started",
      "Total applications submitted",
      "Attendee-to-interest rate",
      "Interest-to-start rate",
      "Start-to-submit rate",
      "Overall attendee-to-submission rate",
    ],
  },
  {
    id: "partner-performance-sheet",
    title: "Partner Performance Sheet",
    purpose:
      "Evaluates each local partner against tier criteria.",
    tracks: [
      "Events hosted",
      "Total attendance",
      "Application conversion rate",
      "Reporting quality score",
      "Responsiveness to ASES HQ",
      "Current tier (Bronze / Silver / Gold)",
    ],
  },
];
